on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Relase"
jobs:
  builds:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: action/checkout@v1
      - uses: action/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "build/app/output/apk/debug/*"
          tag: v1.0.${{ secret.TOKEN}} 




# test
# push to master, main, develop
# pull request on main master